---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      trade
      --strategy-path /freqtrade/user_data/strategies
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --config /freqtrade/user_data/config_adaptive.json
      --strategy AdaptiveBollingerStrategy
